version: "3.9"

services:

  server:
    image: node:latest
    hostname: server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 60
      start_period: 60s
    volumes:
      - ./:/build/source
      - /dev/shm:/dev/shm
    working_dir: /build/source
    entrypoint: ""
    environment:
      - NODE_OPTIONS='--max_old_space_size=4096'
    command: "/bin/bash -c 'npm i && npm run build && npm run preview'"
    profiles:
      - testing
    networks:
      default:
        aliases:
          - server

#  # run tests
  cypress:
   image: cypress/included:10.0.1
   working_dir: /source
   volumes:
     - ./:/source
     - /dev/shm:/dev/shm
   environment:
    - CYPRESS_BASE_URL=http://server:8080
    - NODE_OPTIONS='--max_old_space_size=4096'
   command: run
   profiles:
    - testing
   depends_on:
     server:
       condition: service_healthy
   networks:
     - default

  reports:
    image: node:latest
    entrypoint: ""
    command: "/bin/bash -c 'npm run report:merge && npm run report:generate && npm run report:moveScreenshots && npm run report:moveVideos && npm run report:moveData'"
    working_dir: /build/source
    volumes:
      - ./:/build/source
    environment:
      - NODE_OPTIONS='--max_old_space_size=4096'
    profiles:
      - reports
    networks:
      default:
        aliases:
          - reports

networks:
  default:
