version: "3.9"

services:

  server:
    image: node:latest
    hostname: server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 60
      start_period: 60s
    volumes:
      - ./:/build/source
    working_dir: /build/source
    entrypoint: ""
    command: "/bin/bash -c 'npm i && npm run build && npm run preview'"
    ports:
      - "8080:8080"
    networks:
      default:
        aliases:
          - server

#  # run tests
  cypress:
   image: cypress/included:10.0.1
   working_dir: /source
   volumes:
     - ./:/source
   environment:
    - CYPRESS_BASE_URL=http://server:8080
   command: run || true
   depends_on:
     server:
       condition: service_healthy
   networks:
     - default

  reports:
    image: node:latest
    command: "/bin/bash -c 'npm run posttest'"
    working_dir: /build/source
    volumes:
      - ./:/build/source
    depends_on:
      server:
        condition: service_healthy
      cypress:
        condition: service_completed_successfully
    networks:
      default:
        aliases:
          - reports

networks:
  default:
