
http:
  routers:
    fastapi:
      rule: Host(`api.typerefinery.localhost`)
      # rule: ( Host(`{{ env "TRAEFIK_HOST_DOMAIN" }}`) && PathPrefix(`/api`) ) || Host(`api.localhost`)
      service: fastapi
      entrypoints:
        - web
      middlewares:
        - serviceheaders
    fastapi-https:
      rule: Host(`api.typerefinery.localhost`)
      # rule: ( Host(`{{ env "TRAEFIK_HOST_DOMAIN" }}`) && PathPrefix(`/api`) ) || Host(`api.localhost`)
      service: fastapi
      entrypoints:
        - websecure
      tls: true
      middlewares:
        - serviceheaders

    files:
      rule: Host(`files.typerefinery.localhost`)
      # rule: ( Host(`{{ env "TRAEFIK_HOST_DOMAIN" }}`) && PathPrefix(`/files`) ) || Host(`files.localhost`)
      service: files
      entrypoints:
        - web
      middlewares:
        - serviceheaders
    files-https:
      rule: Host(`files.typerefinery.localhost`)
      # rule: ( Host(`{{ env "TRAEFIK_HOST_DOMAIN" }}`) && PathPrefix(`/files`) ) || Host(`files.localhost`)
      service: files
      entrypoints:
        - websecure
      tls: true
      middlewares:
        - serviceheaders

    postgreadmin:
      rule: Host(`pgadmin.typerefinery.localhost`)
      # rule: ( Host(`{{ env "TRAEFIK_HOST_DOMAIN" }}`) && PathPrefix(`/pgadmin`) ) || Host(`pgadmin.localhost`)
      service: postgreadmin
      entrypoints:
        - web
      middlewares:
        - serviceheaders
    postgreadmin-https:
      rule: Host(`pgadmin.typerefinery.localhost`)
      # rule: ( Host(`{{ env "TRAEFIK_HOST_DOMAIN" }}`) && PathPrefix(`/pgadmin`) ) || Host(`pgadmin.localhost`)
      service: postgreadmin
      entrypoints:
        - websecure
      tls: true
      middlewares:
        - serviceheaders

    bpmn:
      rule: Host(`bpmn.typerefinery.localhost`)
      # rule: ( Host(`{{ env "TRAEFIK_HOST_DOMAIN" }}`) && PathPrefix(`/bpmn`) ) || Host(`bpmn.localhost`)
      service: bpmn
      entrypoints:
        - web
      middlewares:
        - serviceheaders
    bpmn-https:
      rule: Host(`bpmn.typerefinery.localhost`)
      # rule: ( Host(`{{ env "TRAEFIK_HOST_DOMAIN" }}`) && PathPrefix(`/bpmn`) ) || Host(`bpmn.localhost`)
      service: bpmn
      entrypoints:
        - websecure
      tls: true
      middlewares:
        - serviceheaders

    nginx:
      rule: Host(`nginx.typerefinery.localhost`)
      # rule: ( Host(`{{ env "TRAEFIK_HOST_DOMAIN" }}`) && PathPrefix(`/nginx`) ) || Host(`nginx.localhost`)
      service: nginx
      entrypoints:
        - web
    nginx-https:
      rule: Host(`nginx.typerefinery.localhost`)
      # rule: ( Host(`{{ env "TRAEFIK_HOST_DOMAIN" }}`) && PathPrefix(`/nginx`) ) || Host(`nginx.localhost`)
      service: nginx
      entrypoints:
        - websecure
      tls: true

    flow:
      rule: Host(`flow.typerefinery.localhost`)
      # rule: ( Host(`{{ env "TRAEFIK_HOST_DOMAIN" }}`) && PathPrefix(`/flow`) ) || Host(`flow.localhost`)
      service: flow
      entrypoints:
        - web
    flow-https:
      rule: Host(`flow.typerefinery.localhost`)
      # rule: ( Host(`{{ env "TRAEFIK_HOST_DOMAIN" }}`) && PathPrefix(`/flow`) ) || Host(`flow.localhost`)
      service: flow
      entrypoints:
        - websecure
      tls: true

    tms:
      rule: Host(`tms.typerefinery.localhost`)
      # rule: ( Host(`{{ env "TRAEFIK_HOST_DOMAIN" }}`) && PathPrefix(`/tms`) ) || Host(`tms.localhost`)
      service: tms
      entrypoints:
        - web
    tmshttps:
      rule: Host(`tms.typerefinery.localhost`)
      # rule: ( Host(`{{ env "TRAEFIK_HOST_DOMAIN" }}`) && PathPrefix(`/tms`) ) || Host(`tms.localhost`)
      service: tms
      entrypoints:
        - websecure
      tls: true

    jupyterlab:
      rule: Host(`jupyterlab.typerefinery.localhost`)
      # rule: ( Host(`{{ env "TRAEFIK_HOST_DOMAIN" }}`) && PathPrefix(`/nginx`) ) || Host(`nginx.localhost`)
      service: jupyterlab
      entrypoints:
        - web
    jupyterlab-https:
      rule: Host(`jupyterlab.typerefinery.localhost`)
      # rule: ( Host(`{{ env "TRAEFIK_HOST_DOMAIN" }}`) && PathPrefix(`/nginx`) ) || Host(`nginx.localhost`)
      service: jupyterlab
      entrypoints:
        - websecure
      tls: true

    traefikdashboard:
      rule: Host(`traefik.typerefinery.localhost`)
      service: api@internal
      entrypoints: web
      middlewares:
        - error-pages

    error-router:
      rule: HostRegexp(`{host:.+}`)
      priority: 1
      entryPoints:
        - web
      service: noop@internal
      middlewares:
        - error-pages

    error-router-https:
      rule: HostRegexp(`{host:.+}`)
      priority: 1
      entryPoints:
        - websecure
      service: noop@internal
      middlewares:
        - error-pages
      tls: true

    # http-catchall:
    #   rule: "HostRegexp(`{host:.+}`)"
    #   entryPoints:
    #     - web
    #   service: noop@internal

    cms:
      rule: Host(`{{ env "TRAEFIK_HOST_DOMAIN" }}`) || Host(`cms.typerefinery.localhost`)
      # rule: ( Host(`{{ env "TRAEFIK_HOST_DOMAIN" }}`) && PathPrefix(`/cms`) ) || Host(`cms.localhost`)
      # rule: "Host(`cms.user.typerefinery.ai`)"
      entryPoints:
        - web
      service: cms
      middlewares:
        # - stripprefix-cms
        # - replacepath-cms
        - error-pages
        - serviceheaders
    cms-https:
      rule: Host(`{{ env "TRAEFIK_HOST_DOMAIN" }}`) || Host(`cms.typerefinery.localhost`)
      # rule: ( Host(`{{ env "TRAEFIK_HOST_DOMAIN" }}`) && PathPrefix(`/cms`) ) || Host(`cms.localhost`)
      # rule: "Host(`cms.user.typerefinery.ai`)"
      entryPoints:
        - websecure
      service: cms
      tls: true
      middlewares:
        # - stripprefix-cms
        # - replacepath-cms
        - error-pages
        - serviceheaders

  middlewares:
    default:
      chain:
        middlewares:
          # - redirect-to-https
          - error-pages

    error-pages:
      errors:
        query: "/_errors_/{status}.html"
        service: nginx
        status:
          - "400-599"
          # - "403-404"
          # - "500"
          # - "503"

    # cors
    serviceheaders:
      headers:
        accesscontrolalloworiginlist: "*"

    # Redirect to https
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true

    replacepath-cms:
      replacePath:
        path: "/cms"

    stripprefix-cms:
      stripPrefix:
        prefixes:
          - "/cms"

    stripprefix-flow:
      stripPrefix:
        prefixes:
          - "/flow"

    stripprefix-nginx:
      stripPrefix:
        prefixes:
          - "/nginx"

    stripprefix-traefik:
      stripPrefix:
        prefixes:
          - "/traefik"

    # CMS Authentication
    cms-auth:
      forwardAuth:
        address: '{{ env "CMS_URL_AUTH" }}'
        trustForwardHeader: true
        authResponseHeaders:
          - "Websight-Token"
        authRequestHeaders:
          - "Websight-Token"

  services:
    cms:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: '{{ env "CMS_URL" }}'
    fastapi:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: '{{ env "API_URL" }}'
    flow:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: '{{ env "FLOW_HOST_URL" }}'
    tms:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: '{{ env "MESSAGESERVICE_URL" }}'
        sticky:
          cookie: true

    nginx:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: '{{ env "NGINX_URL" }}'

    postgreadmin:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: '{{ env "PGADMIN_URL" }}'

    files:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: '{{ env "FILES_URL" }}'

    bpmn:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: '{{ env "BPMN_URL" }}'

    jupyterlab:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: '{{ env "JUPYTERLAB_URL" }}'

tcp:
  services:
    mongo:
      loadBalancer:
        servers:
          - port: '{{ env "MONGO_PORT" }}'
    typedb:
      loadBalancer:
        servers:
          - port: '{{ env "TYPEDB_PORT" }}'

  routers:
    mongo:
      rule: HostSNI(`*`)
      entrypoints: mongo
      service: mongo
      middlewares: tcp-localhost-ip-whitelist
    typedb:
      rule: HostSNI(`*`)
      entrypoints: typedb
      service: typedb
      middlewares: tcp-localhost-ip-whitelist

  middlewares:
    tcp-localhost-ip-whitelist:
      ipwhitelist:
        sourcerange: 127.0.0.0/1


tls:
  certificates:
    - certFile: {{env "CERT_FILE"}}
      keyFile: {{env "CERT_KEY"}}
