setup.ilm.enabled: false
setup.template.enabled: true
setup.template.name: "nginx-log"
setup.template.pattern: "nginx-log-*"
setup.template.overwrite: true

# filebeat.inputs:
# - type: log
#   enabled: true
#   paths:
#     - ${SERVICE_LOG_PATH}/*.log

filebeat.inputs:
  - type: filestream
    enabled: true
    id: all-logs-collector
    scan_frequency: 1m
    exclude_files: ['combined.log','servicemanager.log']
    prospector.scanner.exclude_files: ['combined.log']
    paths:
      - ${SERVICE_LOG_PATH}/*.log
    parsers:
      - multiline:
          pattern: '^([0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])T(2[0-3]|[01][0-9]):[0-5][0-9]:[0-5][0-9].[0-9]{3}Z )'
          negate: true
          match: after
    processors:
      # - grok:
      #     field: "message"
      #     patterns:
      #       - '%{TIMESTAMP_ISO8601:timestamp}${SPACE}%{LOGLEVEL:level}${SPACE}%{GREEDYDATA:content}'
      - dissect:
          tokenizer: "%{@timestamp} %{level} %{label} -- %{message}"
          field: "message"
          target_prefix: ""
          overwrite_keys: true
      - timestamp:
          field: "@timestamp"
          layouts:
            - '2006-01-02T15:04:05Z'
            - '2006-01-02T15:04:05.999Z'
            - '2006-01-02T15:04:05.999-07:00'
            - '2024-07-11T14:25:08.092898400+00:00'
          test:
            - '2024-07-11T13:25:15Z'
            - '2024-07-11T13:25:15.140Z'
            - '2024-07-11T13:25:15.140456+02:00'
            - '2024-07-11T14:25:08.092898400+00:00'
      - decode_json_fields:
          fields: ["message"]
          target: ""
          process_array: true
          max_depth: 4
          add_error_key: false
      # - copy_fields:
      #     fields:
      #       - from: dissect_level
      #         to: event.level
      #       - from: dissect_message
      #         to: event.message
      #       - from: dissect_timestamp
      #         to: event.timestamp
      #       - from: dissect_service
      #         to: event.service
      #     fail_on_error: false
      #     ignore_missing: true
      - drop_fields:
          fields: ["message"]

  - type: filestream
    enabled: true
    id: json-combined-collector
    paths:
      - ${SERVICE_LOG_PATH}/combined.log
    parsers:
      - ndjson:
          keys_under_root: true
          message_key: message
          target: ""
          add_error_key: true
    processors:
    #   # - json:
    #   #     keys_under_root: true
    #   #     add_error_key: true
    #   #     message_key: message
    #   #     overwrite_keys: true
      - decode_json_fields:
          fields: ["message"]
          target: ""
          process_array: true
          max_depth: 4
          add_error_key: false

output.elasticsearch:
  hosts: ["${OPENOBSERVE_URL}"]
  timeout: 10
  path: "/api/default/"
  index: "default"
  username: "${OPENOBSERVE_ZO_ROOT_USER_EMAIL}"
  password: "${OPENOBSERVE_ZO_ROOT_USER_PASSWORD}"
