
  # After registering a name on build.snapcraft.io, commit an uncommented line:
  # name: typerefinery
  base: core22 # the base snap is the execution environment for this snap
  type: app
  version: '2023.3.31' # just for humans, typically '1.2+git' or '1.3.2'
  name: typerefinery
  title: TypeRefinery
  summary: Data Visualisation reimagined. # 79 char long summary
  description: |
    Typerefinery brings together the power of TypeDB and TypeQL with the ease of use of a no-code interface. It's a platform that integrates TypeDB into fully functional knowledge graph platform and enabled creation and syndication of knowledge experiences.
    Typerefinery seeks to bring best of breed open source tools integerated into a coherent platform. We focus on integration and data driven workflow for knowledge graph development. This approach enables rapid development of knowledge graphs and knowledge experiences.
    We want to enable you to create knowledge graphs and help you develop experiences that will help you to make better decisions and help you share this knowledge with others.
    We have created a platform that enables technical integration of best of breed tools for specific tasks. We have purposly avoided the creation of a monolithic platform that tries to do everything. We have focused on integration and data driven workflow for creating rich experiences. We have aimed to create a platform that is easy to use and easy to extend by us and by you.
    We focused on ensuring that the platform can be run as an application and as a service. We have also focused on ensuring that the platform can be run on premise and in the cloud.
  grade: devel # must be 'stable' to release into candidate/stable channels
  confinement: devmode # use 'strict' once you have the right plugs and slots
  icon: electron/static/assets/tray_icon.png
  contact: devops.typerfineryai@gmail.com
  source-code: https://github.com/typerefinery-ai/typerefinery
  website: https://typerefinery.ai
  license: Apache-2.0
  parts:
    my-part:
      # See 'snapcraft plugins'
      plugin: nil

